# Site settings
title: Laila Sprejer
description: 'Welcome to my blog!'
url: 'https://sprejerlaila.github.io/jekyll-uno'
baseurl: 'https://sprejerlaila.github.io/jekyll-uno'
google_analytics: 'UA-145403173-1'
disqus_shortname: 'laila-3'

author:
  name: 'Laila Sprejer'
  email: sprejerlaila@gmail.com.com
  #twitter_username: joshgerdes
  #facebook_username: joshgerdes
  github_username: sprejerlaila
  linkedin_username: lailasprejer

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
